export const alumniList = [
  {
    id: '1',
    code: 'A01',
    name: 'Alumni Name 01',
    designation: 'PLC & Automation Engineer',
    subDesignation: 'Industrial Automation & Robotics',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '2+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '2',
    code: 'A02',
    name: 'Alumni Name 02',
    designation: 'SCADA Specialist',
    subDesignation: 'Control & Data Acquisition',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '3+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '3',
    code: 'A03',
    name: 'Alumni Name 03',
    designation: 'Substation Engineer',
    subDesignation: 'Power Grid & Distribution',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '1+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '4',
    code: 'A04',
    name: 'Alumni Name 04',
    designation: 'Electrical Project Engineer',
    subDesignation: 'High Voltage Systems',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '4+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '5',
    code: 'A05',
    name: 'Alumni Name 05',
    designation: 'BMS Test Engineer',
    subDesignation: 'Building Automation Systems',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '2+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '6',
    code: 'A06',
    name: 'Alumni Name 06',
    designation: 'Solar PV Designer',
    subDesignation: 'Renewable Energy Systems',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '1.5+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '7',
    code: 'A07',
    name: 'Alumni Name 07',
    designation: 'Instrumentation Engineer',
    subDesignation: 'Process Control Systems',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '3+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '8',
    code: 'A08',
    name: 'Alumni Name 08',
    designation: 'Embedded Systems Developer',
    subDesignation: 'Microcontroller & IoT',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '2+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '9',
    code: 'A09',
    name: 'Alumni Name 09',
    designation: 'Energy Auditor',
    subDesignation: 'Industrial Efficiency & Conservation',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '5+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '10',
    code: 'A10',
    name: 'Alumni Name 10',
    designation: 'VFD Specialist',
    subDesignation: 'Motor Drives & Control',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '2+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '11',
    code: 'A11',
    name: 'Alumni Name 11',
    designation: 'HVAC Automation Engineer',
    subDesignation: 'Climate Control & Optimization',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '3+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '12',
    code: 'A12',
    name: 'Alumni Name 12',
    designation: 'Power System Analyst',
    subDesignation: 'Load Flow & Protection',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '1+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '13',
    code: 'A13',
    name: 'Alumni Name 13',
    designation: 'Safety & Quality Engineer',
    subDesignation: 'Compliance & Standard Compliance',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '4+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '14',
    code: 'A14',
    name: 'Alumni Name 14',
    designation: 'Solar Design Engineer',
    subDesignation: 'Solar Power Plant Design',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '2+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '15',
    code: 'A15',
    name: 'Alumni Name 15',
    designation: 'Robotics Application Engineer',
    subDesignation: 'Automated Manufacturing',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '2+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '16',
    code: 'A16',
    name: 'Alumni Name 16',
    designation: 'Fire & Safety Automation Specialist',
    subDesignation: 'Protection Systems',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '3+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '17',
    code: 'A17',
    name: 'Alumni Name 17',
    designation: 'Industrial IoT Specialist',
    subDesignation: 'Smart Factory Solutions',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '1+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  },
  {
    id: '18',
    code: 'A18',
    name: 'Alumni Name 18',
    designation: 'Maintenance Engineer',
    subDesignation: 'Building Management Systems',
    description: 'A UE Training alumni member who has developed practical, industry-focused engineering skills through professional training, projects and community participation.',
    company: 'Company / Institute Name',
    university: 'University Name',
    experience: '1+ years',
    location: 'Bangladesh',
    image: 'https://via.placeholder.com/150'
  }
];